export const ENV_PROTOCOL_KEY = 'PROTOCOL';
export const ENV_HOST_KEY = 'HOST';

export const ENV_JWT_SECRET_KEY = 'JWT_SECRET';

export const ENV_HASH_ROUNDS_KEY = 'HASH_ROUND';

export const ENV_DB_HOST_KEY = 'DB_HOST';

export const ENV_DB_PORT_KEY = 'DB_PORT';

export const ENV_DB_USERNAME_KEY = 'DB_USERNAME';

export const ENV_DB_PASSWORD_KEY = 'DB_PASSWORD';

export const ENV_DB_DATABASE_KEY = 'DB_DATABASE';

export const ENV_KAKAO_CLIENT_ID_KEY = 'KAKAO_CLIENT_ID';

export const ENV_KAKAO_CLIENT_SECRET_KEY = 'KAKAO_CLIENT_SECRET';

export const ENV_KAKAO_REDIRECT_URL_KEY = 'KAKAO_REDIRECT_URL';
